### ISSUE TITLE
Remove/Reduce Nested Scrolling of Tables

### ISSUE THREAD

**Issue by ZHoob2004** [corygrant/DingoConfigurator#22]
When opening the application, many of the settings tables are smaller than their contents resulting in nested scroll bars.

I propose that the tables be resized to fit their contents and the main scroll bar be the only one.

**Comment by corygrant** [comment]
Try this release. 
https://github.com/corygrant/DingoConfigurator/releases/tag/v0.1.2.0

Are you able to build from the sources? 
If so then I won't create a release for small changes like this until I get a few built up.

**Comment by ZHoob2004** [comment]
I haven't tried to build the configurator yet, but it's on my list.

**Comment by ZHoob2004** [comment]
Just checked it out, I like it.

**Comment by corygrant** [comment]
@ZHoob2004 great! I'll close this then
