### ISSUE TITLE
Cannot connect to DingoPDM via USB

### ISSUE THREAD

**Issue by graemecoard** [corygrant/DingoConfigurator#37]
Hi, 
First of all thanks for making this project open source, I've been looking for something like this for a while.

I've made a few boards for myself, and have uploaded firmware through STM32CubeProgrammer, all seems good.
Green status light comes on when USB connected.

Tried powering board with 12v as well to make sure that's not an issue. The board appears in device selection for USB but the connect button is greyed out.

Any ideas?
Thanks

**Comment by corygrant** [comment]
Try adding a PDM device to the device tree, you'll need to enter a name and a valid CAN base ID. The default base ID is 2000. 

Its a bit confusing, but the Connect button is not enabled if there's nothing in the device tree. 

The USB data is just a replication of the CAN data so it appears like one device communicating over CAN to the Configurator. 
The idea is that you can have multiple devices in the tree if your vehicle uses more than one. If you connect with CAN you can communicate to all of them at once. If you connect with USB, I try to match the base ID with the base ID in the USB data. 

Would love to see what you're putting them in, please share on Discord if you can!

**Comment by graemecoard** [comment]
Ah great, all is working now. 
Will have to head over to the discord and will put some pics up when its all done, thanks!
